baseURL = 'https://vegasword.github.io/blog'
locale = 'en-us'
title = 'vegasword - Blog'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome/v2"

[params]
  goToTop = true